language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: 7.1

env:
    global:
        - APP_ENV=test
        - APP_DEBUG=0

install:
    - composer install --prefer-dist;



script:
    - vendor/bin/phpunit
    - vendor/bin/php-cs-fixer fix --config=.php_cs --dry-run --diff
