language: php

services:
    - redis-server

env:
    global:
        - SYMFONY_PHPUNIT_REMOVE="symfony/yaml"
        - APP_ENV=test

matrix:
    include:
        - php: 7.4

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - bin/.phpunit

install: composer install --prefer-dist --no-interaction

script:
    - composer validate
    - make test
    - make cs_dry_run

branches:
    only:
        - master
