language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

matrix:
    include:
        - php: hhvm
        - php: 5.6
        - php: 7.0

install:
    - composer --prefer-source update;
