monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: error_log
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        error_log:
            type: error_log
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
