# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    env(REDIS_URL): redis://localhost:6379

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    Predis\Client:
        arguments:
            $parameters: '%env(REDIS_URL)%'

    Predis\ClientInterface:
        alias: Predis\Client

    session.handler.predis:
        class: Predis\Session\Handler
        autowire: true

    GuzzleHttp\Client:
        arguments:
            $config: {timeout: 2}

    GuzzleHttp\ClientInterface:
        alias: GuzzleHttp\Client

    CL\Slack\Transport\ApiClient:
        arguments:
            $token: ~
