homepage:
    path:     /
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController:homepage }

hall_of_fame:
    path:     /hall-of-fame
    defaults: { _controller: JoliCode\SecretSanta\Controller\ContentController:hallOfFame }

run:
    path:     /run/{application}
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController:run }

finish:
    path:     /finish/{hash}
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController:finish }

retry:
    path:     /retry/{hash}
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController:retry }

spoil:
    path:     /spoil
    defaults: { _controller: JoliCode\SecretSanta\Controller\SantaController:spoil }

slack_authenticate:
    path:     /auth/slack
    defaults: { _controller: JoliCode\SecretSanta\Controller\SlackController:authenticate }

discord_authenticate:
    path:     /auth/discord
    defaults: { _controller: JoliCode\SecretSanta\Controller\DiscordController:authenticate }

teams_start:
    path:     /teams/start
    defaults: { _controller: JoliCode\SecretSanta\Controller\TeamsController:start }

teams_incoming_bot:
    path:     /teams/incoming_bot
    defaults: { _controller: JoliCode\SecretSanta\Controller\TeamsController:incomingBot }

teams_init:
    path:     /teams/init/{id}
    defaults: { _controller: JoliCode\SecretSanta\Controller\TeamsController:init }
