homepage:
    path:     /
    defaults: { _controller: Joli\SlackSecretSanta\Controller\ContentController:homepage }

hall_of_fame:
    path:     /hall-of-fame
    defaults: { _controller: Joli\SlackSecretSanta\Controller\ContentController:hallOfFame }

run:
    path:     /run
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:run }

finish:
    path:     /finish/{hash}
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:finish }

retry:
    path:     /retry/{hash}
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:retry }

authenticate:
    path:     /auth
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:authenticate }

spoil:
    path:     /spoil
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:spoil }
