homepage:
    path:     /
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:homepage }

run:
    path:     /run
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:run }

finish:
    path:     /finish/{hash}
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:finish }

summary:
    path:     /summary/{hash}
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:summary }

retry:
    path:     /retry/{hash}
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:retry }

authenticate:
    path:     /auth
    defaults: { _controller: Joli\SlackSecretSanta\Controller\SantaController:authenticate }
